# Please note:
# This setup seems to be intended for use during backend development.
# The complete environment including backend and frontend containers
# is located in the parent directory.

version: '3'
services:
  minio:
    image: docker.io/bitnami/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_password
      - MINIO_DEFAULT_BUCKETS=test
