name: Test and build SEE

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [master]
  workflow_dispatch:
    inputs:
      windows:
        description: 'Create Windows build?'
        default: true
        type: boolean
      linux:
        description: 'Create Linux build?'
        default: true
        type: boolean

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  setup:
    name: Setup Repository
    runs-on: self-hosted
    outputs:
      runner: ${{ steps.remember.outputs.runner }}
    steps:
      - name: Fix permissions
        shell: bash
        run: sudo /mnt/scripts/set-work-permissions.sh
      - name: Setup GitLab LFS
        run: |
          echo "$CREDENTIALS" > ~/.git-credentials
          git config --global credential.helper store
          git config --global lfs.url ${CREDENTIALS}project-see/see-lfs.git/info/lfs
        env:
          # NOTE: must be of the form https://koschke:token-here@gitlab.informatik.uni-bremen.de/
          CREDENTIALS: ${{secrets.GITLAB_LFS_TOKEN}}
      - uses: actions/checkout@v3
        name: Checkout Repository
        with:
          lfs: true
          fetch-depth: 0
      - name: Confirm LFS pull
        run: git lfs pull
      - name: Remember runner
        id: remember
        # We remember this to make sure all jobs are run on the same machine.
        run: echo "runner=${{ runner.name }}" >> $GITHUB_OUTPUT
  gitscripts:
    name: Run GitScript checks
    runs-on: ${{ needs.setup.outputs.runner }}
    needs: [setup]
    if: ${{ github.event_name != 'workflow_dispatch' }}
    steps:
      - name: Run GitScripts checks
        run: ./GitScripts/run_all
  static:
    name: Run static checks
    runs-on: self-hosted
    if: ${{ !github.event.pull_request.draft && github.event_name != 'workflow_dispatch' &&  github.ref != 'refs/heads/master' }}
    permissions:
      contents: read
      issues: read
      pull-requests: write
    steps:
      - name: Collect bad patterns
        run: |
          if [ -n $GITHUB_BASE_REF ] && ! PATTERNS=$(curl -H 'Accept: application/vnd.github.v3.diff' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -f 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}' | ./GitScripts/check_for_bad_patterns.py); then
            DELIMITER=7MApgggGyx6C0
            echo "PATTERNS<<$DELIMITER" >> $GITHUB_ENV
            echo "$PATTERNS" >> $GITHUB_ENV
            echo "$DELIMITER" >> $GITHUB_ENV
          else
            echo "PATTERNS=none" >> $GITHUB_ENV
          fi
      - uses: actions/github-script@v6
        name: Check for bad patterns
        with:
          retries: 3
          script: |
            const PATTERNS = process.env.PATTERNS;
            const helper = require('./GitScripts/review_helper.js');
            if (PATTERNS === "none") {
              console.log("Found no bad patterns in changed files.");
            } else {
              let comments = JSON.parse(PATTERNS);
              console.log("::warning::Found " + comments.length + " bad patterns!");
              if (context.ref === 'refs/heads/master') {
                console.log("However, we are on master, so we ignore them.");
              } else {
                await helper.filter_out_existing_comments(github, context, comments);
                if (comments.length > 0) {
                  console.log("Submitting PR review...");
                  let limitMessage = '';
                  if (comments.length > 50) {
                    limitMessage = `\n\n**NOTE: Only the first 50 (out of ${comments.length}) review comments are included.** `;
                    limitMessage += 'Remaining comments will appear when the CI is triggered next.';
                    comments.splice(50);
                  }
                  github.rest.pulls.createReview({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: context.issue.number,
                    event: 'COMMENT',
                    body: 'There are a few bad patterns I found which you should check.' + limitMessage,
                    comments: comments
                  });
                } else {
                  console.log("After filtering, no new comments are left. Not submitting a review.");
                }
              }
            }

  test:
    name: Run editmode tests
    runs-on: ${{ needs.setup.outputs.runner }}
    needs: [setup, gitscripts]
    if: ${{ ! github.event.pull_request.draft && github.event_name != 'workflow_dispatch' }}
    permissions: write-all
    steps:
      - uses: actions/cache@v3
        name: Cache Library
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 11
        with:
          path: ./Library
          key: Library-SEE-Tests-${{ hashFiles('./ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-SEE-Tests
            Library-SEE
      - uses: game-ci/unity-test-runner@v2
        timeout-minutes: 45
        name: Run Tests
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.os }} Test Results
          testMode: EditMode  # PlayMode tests get stuck in batchmode
          customParameters: -testCategory "!NonDeterministic"
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;assemblyFilters:+SEE'
      - uses: actions/upload-artifact@v3
        name: Upload test results
        if: ${{ !cancelled() }}
        with:
          name: Test results for ${{ matrix.os }}
          path: ${{ steps.tests.outputs.artifactsPath }}
      - uses: actions/upload-artifact@v3
        name: Upload coverage results
        if: github.ref == 'refs/heads/master'
        with:
          name: Coverage results
          path: ${{ steps.tests.outputs.coveragePath }}

  setup_build_targets:
    name: Setup build targets
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: self-hosted
    outputs:
      targetPlatforms: ${{ steps.rememberPlatforms.outputs.targetPlatforms }}
    steps:
      - id: rememberPlatforms
        name: Choose platforms for which to create builds
        run: |
          if ${{ github.event_name != 'workflow_dispatch' }}; then
            # Include all target platforms.
            echo 'targetPlatforms=["StandaloneWindows64", "StandaloneLinux64"]' >> $GITHUB_OUTPUT
          else
            # Set targetPlatform based on inputs.
            targetPlatforms=()
            if ${{ github.event.inputs.windows == true }}; then
                targetPlatforms+=("StandaloneWindows64")
            fi
            if ${{ github.event.inputs.linux == true }}; then
                targetPlatforms+=("StandaloneLinux64")
            fi
            echo "targetPlatforms=$(jq --compact-output --null-input '$ARGS.positional' --args -- ${targetPlatforms[@]})" >> $GITHUB_OUTPUT
          fi


  build:
    name: Build release
    runs-on: ${{ needs.setup.outputs.runner }}
    needs: [setup, setup_build_targets, test, gitscripts]
    strategy:
      matrix:
        targetPlatform: ${{ fromJson(needs.setup_build_targets.outputs.targetPlatforms) }}
    if: ${{ ! github.event.pull_request.draft }}
    steps:
      - name: Cleanup any modifications
        run: |
          sudo /mnt/scripts/set-work-permissions.sh  # Permissions may be messed up here
          git reset --hard ${{ github.sha }}  # Test or previous build may have changed files
          git clean -fd
          rm -rf build || true  # Try deleting any previous build
      - uses: game-ci/unity-builder@v2
        timeout-minutes: 45
        name: Build project
        id: build
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v3
        name: Upload build
        # Upload only if on master or if manually triggered
        if: ${{ github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch' }}
        with:
          name: SEE-${{ matrix.targetPlatform }}-${{ github.sha }}
          path: build/${{ matrix.targetPlatform}}
          retention-days: 7  # Due to high space usage.

  cleanup:
    name: Cleanup
    runs-on: ${{ needs.setup.outputs.runner }}
    if: ${{ always() }}
    needs: [setup, test, build]   # "test" and "build" two use docker and sometimes mess up permissions.
    strategy:
      fail-fast: false
    steps:
      - name: Kill Unity
        if: always()
        shell: bash
        run: ./.github/scripts/stop-docker.sh
      - name: Fix permissions
        if: always()
        shell: bash
        run: sudo /mnt/scripts/set-work-permissions.sh

